version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo/db:/data/db
  
  web:
    build:
      context: ./idreesia-web
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  jobs:
    build:
      context: ./idreesia-jobs
    ports:
      - "3002:3002"
    depends_on:
      - mongo
