version: "3"
services:
  mongo:
    build:
      context: ./containers/mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev:/data/db

  mongo-express:
    build:
      context: ./containers/mongo-express
    depends_on:
      - mongo
    ports:
      - "8000:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=erp-admin
      - ME_CONFIG_BASICAUTH_PASSWORD=fairly long password

volumes:
  mongo-dev: {}
