const { FlatCompat } = require('@eslint/eslintrc');
const js = require('@eslint/js');
const babelParser = require('@babel/eslint-parser');
const globals = require('globals');

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

module.exports = [
  {
    ignores: ['ecosystem.config.js', 'node_modules/**', '**/workbox-v4.3.1/**'],
  },
  ...compat.extends('airbnb', 'prettier'),
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parser: babelParser,
      parserOptions: {
        requireConfigFile: false,
        babelOptions: {
          babelrc: false,
          configFile: false,
          plugins: ['@babel/plugin-syntax-jsx'],
        },
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.mocha,
        Meteor: 'readonly',
        Mongo: 'readonly',
        Accounts: 'readonly',
        ServiceConfiguration: 'readonly',
        Assets: 'readonly',
        Package: 'readonly',
        Npm: 'readonly',
        check: 'readonly',
        Match: 'readonly',
      },
    },
    settings: {
      react: {
        version: '17.0',
      },
    },
    rules: {
      'class-methods-use-this': 'off',
      'arrow-body-style': 'off',
      'comma-dangle': 'off',
      'constructor-super': 'off',
      'max-len': 'off',
      'global-require': 'off',
      'no-await-in-loop': 'off',
      'no-bitwise': ['error', { allow: ['~'] }],
      'no-class-assign': 'off',
      'no-confusing-arrow': 'off',
      'no-constructor-return': 'off',
      'no-continue': 'off',
      'no-debugger': 'off',
      'no-empty-pattern': 'off',
      'no-else-return': 'off',
      'no-mixed-operators': 'off',
      'no-prototype-builtins': 'off',
      'no-plusplus': 'off',
      'no-return-await': 'off',
      'no-shadow': 'off',
      'no-underscore-dangle': 'off',
      'no-unused-vars': ['error', { args: 'none' }],
      'no-useless-escape': 'off',
      'no-use-before-define': 'off',
      'no-restricted-globals': 'off',
      'no-restricted-properties': 'off',
      'no-restricted-syntax': 'off',
      'prefer-object-spread': 'off',
      'prefer-destructuring': 'off',
      'prefer-promise-reject-errors': 'off',
      'spaced-comment': 'off',
      'import/export': 'off',
      'import/extensions': 'off',
      'import/first': 'off',
      'import/no-cycle': 'off',
      'import/no-absolute-path': 'off',
      'import/no-duplicates': 'off',
      'import/no-extraneous-dependencies': 'off',
      'import/no-named-default': 'off',
      'import/no-named-as-default': 'off',
      'import/no-named-as-default-member': 'off',
      'import/no-mutable-exports': 'off',
      'import/no-unresolved': 'off',
      'import/no-useless-path-segments': 'off',
      'import/prefer-default-export': 'off',
      'jsx-a11y/alt-text': 'off',
      'jsx-a11y/anchor-has-content': 'off',
      'jsx-a11y/anchor-is-valid': 'off',
      'jsx-a11y/control-has-associated-label': 'off',
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/iframe-has-title': 'off',
      'jsx-a11y/label-has-for': 'off',
      'jsx-a11y/mouse-events-have-key-events': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
      'jsx-a11y/no-noninteractive-element-interactions': 'off',
      'react/default-props-match-prop-types': 'off',
      'react/destructuring-assignment': 'off',
      'react/function-component-definition': 'off',
      'react/jsx-curly-brace-presence': 'off',
      'react/jsx-closing-tag-location': 'off',
      'react/jsx-fragments': 'off',
      'react/forbid-prop-types': 'off',
      'react/jsx-indent': 'off',
      'react/jsx-filename-extension': 'off',
      'react/jsx-no-useless-fragment': 'off',
      'react/jsx-pascal-case': 'off',
      'react/no-access-state-in-setstate': 'off',
      'react/no-array-index-key': 'off',
      'react/no-arrow-function-lifecycle': 'off',
      'react/no-danger': 'off',
      'react/no-deprecated': 'off',
      'react/jsx-no-comment-textnodes': 'off',
      'react/no-find-dom-node': 'off',
      'react/no-render-return-value': 'off',
      'react/no-string-refs': 'off',
      'react/no-this-in-sfc': 'off',
      'react/no-unescaped-entities': 'off',
      'react/no-unstable-nested-components': 'off',
      'react/no-unused-state': 'off',
      'react/no-unused-class-component-methods': 'off',
      'react/no-unused-prop-types': 'off',
      'react/prop-types': 'off',
      'react/require-default-props': 'off',
      'react/sort-comp': 'off',
      'react/prefer-stateless-function': [
        'error',
        { ignorePureComponents: true },
      ],
      'react/prefer-es6-class': 'off',
      'react/jsx-props-no-spreading': 'off',
      'react/static-property-placement': 'off',
      'react/state-in-constructor': 'off',
      'lines-between-class-members': 'off',
    },
  },
];
