version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/idreesia-erp/idreesia-web

    steps:
      - checkout:
          path: ~/idreesia-erp

      # Install Meteor
      - run: "curl https://install.meteor.com | /bin/sh"

      # Build Web
      # - restore_cache:
      #    key: web-dependencies-{{ checksum "package.json" }}

      - run:
          command: "meteor npm install"

      # - save_cache:
      #    paths:
      #      - node_modules
      #    key: web-dependencies-{{ checksum "package.json" }}

      - run:
          command: meteor npm build

      # Login to Docker
      - run:
          command: docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD

      # Build and push the web image to docker hub
      - run:
          command: |
            "docker build -t faysalahmad/idreesia-web ."
            "docker push faysalahmad/idreesia-web"
