version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - run:
          command: |
            "cd /home/circleci/idreesia"
            "ls"

      # Install Meteor
      - run: "curl https://install.meteor.com | /bin/sh"

      # Build Web
      - run:
          command: "cd /home/circleci/idreesia/idreesia-web"
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: "meteor npm install"

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: meteor npm build

      # Build Jobs
      - run:
          command: "cd /home/circleci/idreesia/idreesia-jobs"
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: "meteor npm install"

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: meteor npm build

      # Login to Docker
      - run:
          command: docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD

      # Build and push the web image to docker hub
      - run:
          command: |
            "cd /home/circleci/idreesia/idreesia-web"
            "docker build -t faysalahmad/idreesia-web ."
            "docker push faysalahmad/idreesia-web"

      # Build and push the web image to docker hub
      - run:
          command: |
            "cd /home/circleci/idreesia/idreesia-web"
            "docker build -t faysalahmad/idreesia-jobs ."
            "docker push faysalahmad/idreesia-jobs"
