version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15.1

    working_directory: ~/idreesia-web

    steps:
      - checkout

      # Install Meteor
      - run: "curl https://install.meteor.com | /bin/sh"

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: "meteor npm install"

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: meteor npm build
