// @ts-nocheck
import gql from 'graphql-tag';

export default gql`
enum Permission {
  ADMIN_VIEW_USERS_AND_GROUPS
  ADMIN_MANAGE_USERS_AND_GROUPS
  ADMIN_MANAGE_PHYSICAL_STORES
  ADMIN_MANAGE_CITIES

  HR_MANAGE_SETUP_DATA
  HR_DELETE_DATA
  HR_VIEW_AUDIT_LOGS
  HR_VIEW_KARKUNS
  HR_MANAGE_KARKUNS
  HR_VIEW_EMPLOYEES
  HR_MANAGE_EMPLOYEES
  HR_APPROVE_SALARIES

  IN_MANAGE_SETUP_DATA
  IN_MANAGE_STOCK_ITEMS
  IN_VIEW_ISSUANCE_FORMS
  IN_MANAGE_ISSUANCE_FORMS
  IN_APPROVE_ISSUANCE_FORMS
  IN_VIEW_PURCHASE_FORMS
  IN_MANAGE_PURCHASE_FORMS
  IN_APPROVE_PURCHASE_FORMS
  IN_VIEW_STOCK_ADJUSTMENTS
  IN_MANAGE_STOCK_ADJUSTMENTS
  IN_APPROVE_STOCK_ADJUSTMENTS

  SECURITY_DELETE_DATA
  SECURITY_MANAGE_SETUP_DATA
  SECURITY_VIEW_AUDIT_LOGS
  SECURITY_VIEW_USERS
  SECURITY_MANAGE_USERS
  SECURITY_VIEW_KARKUN_VERIFICATION
  SECURITY_VIEW_VISITORS
  SECURITY_MANAGE_VISITORS
  SECURITY_VIEW_MEHFILS
  SECURITY_MANAGE_MEHFILS
}
`;
